name: Run tests
run-name: Run frontend tests ${{github.repository}}
on:
  push:
    branches:
      - main
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests and capture output
        id: run-tests
        working-directory: ./frontend
        run: npm test -- --json --outputFile=results.json

      - name: Upload test result
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: results.json
